# for port mapping, left side is host, right side is container
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    networks:
      - public
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:plex
      - TP_THEME=dracula
    volumes:
      - /mnt/plex/config:/config
      - /mnt/plex/transcode:/transcode
      - /mnt/storage/media:/data/media
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.engager.rooday.com`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls.certresolver=cloudflare
  kometa:
    image: kometateam/kometa:latest
    container_name: kometa
    networks:
      - public
    environment:
      - TZ=America/New_York
    volumes:
      - ./data/kometa:/config
    restart: unless-stopped
    labels:
      - traefik.enable=false
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    networks:
      - public
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:tautulli
      - TP_THEME=dracula
    volumes:
      - ./data/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.engager.rooday.com`)
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
      - traefik.http.routers.tautulli.entrypoints=websecure
      - traefik.http.routers.tautulli.tls.certresolver=cloudflare
  synclounge:
    image: lscr.io/linuxserver/synclounge:latest
    container_name: synclounge
    networks:
      - public
    environment:
      - TZ=America/New_York
      - AUTH_LIST=${SYNCLOUNGE_AUTH_LIST}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:synclounge
      - TP_THEME=dracula
    ports:
      - 8088:8088
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.synclounge.rule=Host(`synclounge.engager.rooday.com`)
      - traefik.http.services.synclounge.loadbalancer.server.port=8088
      - traefik.http.routers.synclounge.entrypoints=websecure
      - traefik.http.routers.synclounge.tls.certresolver=cloudflare
  # requestrr:
  #   image: thomst08/requestrr
  #   container_name: requestrr
  #   networks:
  #     - public
  #     - private
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/New_York
  #   volumes:
  #     - ./data/requestrr:/root/config
  #   ports:
  #     - 4545:4545
  #   restart: unless-stopped
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.requestrr.rule=Host(`requestrr.engager.rooday.com`)
  #     - traefik.http.services.requestrr.loadbalancer.server.port=4545
  #     - traefik.http.routers.requestrr.entrypoints=websecure
  #     - traefik.http.routers.requestrr.tls.certresolver=cloudflare
  #     - traefik.docker.network=public
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    networks:
      - public
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PASSWORD=${LIBRESPEED_PASSWORD}
    volumes:
      - ./data/librespeed:/config
    ports:
      - 8567:80
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.librespeed.rule=Host(`librespeed.engager.rooday.com`)
      - traefik.http.services.librespeed.loadbalancer.server.port=80
      - traefik.http.routers.librespeed.entrypoints=websecure
      - traefik.http.routers.librespeed.tls.certresolver=cloudflare
  corsproxy:
    image: imjacobclark/cors-container:latest
    container_name: corsproxy
    networks:
      - public
    ports:
      - 3333:3000
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.corsproxy.rule=Host(`corsproxy.engager.rooday.com`)
      - traefik.http.services.corsproxy.loadbalancer.server.port=3000
      - traefik.http.routers.corsproxy.entrypoints=websecure
      - traefik.http.routers.corsproxy.tls.certresolver=cloudflare
  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    container_name: PlexAutoLanguages
    networks:
      - public
    environment:
      - PLEX_URL=http://plex:32400
      - PLEX_TOKEN=${PAL_PLEX_TOKEN}
      - TZ=America/New_York
    volumes:
      - ./data/plex-auto-languages:/config
    restart: unless-stopped
    labels:
      - traefik.enable=false
